#+title: Doom Emacs Configuration
* Table of contents :toc:
- [[#appearance][Appearance]]
  - [[#dashboard][Dashboard]]
  - [[#font][Font]]
  - [[#transparency][Transparency]]
  - [[#doom-theme][Doom theme]]
  - [[#line-numbering][Line numbering]]
- [[#ivy][Ivy]]
- [[#imenu][IMenu]]
- [[#org-mode][Org-mode]]
  - [[#basic-org-mode-setup][Basic org-mode setup]]
  - [[#notifications][Notifications]]
  - [[#org-capture-templates][Org capture templates]]
  - [[#archiving][Archiving]]
  - [[#refile-targets][Refile targets]]
  - [[#org-modern][Org-modern]]
  - [[#org-agenda][Org-agenda]]
  - [[#org-super-agenda][Org-super-agenda]]
  - [[#org-roam][Org-roam]]
  - [[#org-journal][Org-journal]]
  - [[#miscellaneous][Miscellaneous]]
- [[#latex][LaTeX]]
  - [[#higher-resolution-org-mode-latex-preview][Higher resolution Org-mode LaTeX preview]]
  - [[#make-org-mode-latex-previews-work-better-with-black-themes][Make Org-mode LaTeX previews work better with black themes]]
  - [[#highlight-latex-fragments][Highlight LaTeX fragments]]
  - [[#preview-tikz-plots][Preview TikZ plots]]
- [[#novel][Nov.el]]
- [[#elfeed][Elfeed]]
  - [[#keybindings][Keybindings]]
  - [[#elfeed-org][Elfeed-org]]
  - [[#elfeed-score][Elfeed-score]]
  - [[#capture-to-org-roam][Capture to Org-roam]]
- [[#beancount][Beancount]]
- [[#lsp][LSP]]
  - [[#nix][Nix]]
  - [[#lsp-ui][LSP UI]]
- [[#company][Company]]
- [[#miscellaneous-1][Miscellaneous]]
  - [[#rainbow-mode][Rainbow mode]]
  - [[#aggressive-indent-mode][Aggressive indent mode]]
  - [[#better-copy-paste-keybinds][Better copy-paste keybinds]]
  - [[#default-shell][Default shell]]

* Appearance
** Dashboard
#+begin_src emacs-lisp
(defun dysthesis/dashboard-setup ()
  (let* ((banner '("                                   "
	           "                                   "
	           "                                   "
	           "   ⣴⣶⣤⡤⠦⣤⣀⣤⠆     ⣈⣭⣿⣶⣿⣦⣼⣆          "
	           "    ⠉⠻⢿⣿⠿⣿⣿⣶⣦⠤⠄⡠⢾⣿⣿⡿⠋⠉⠉⠻⣿⣿⡛⣦       "
	           "          ⠈⢿⣿⣟⠦ ⣾⣿⣿⣷    ⠻⠿⢿⣿⣧⣄     "
	           "           ⣸⣿⣿⢧ ⢻⠻⣿⣿⣷⣄⣀⠄⠢⣀⡀⠈⠙⠿⠄    "
	           "          ⢠⣿⣿⣿⠈    ⣻⣿⣿⣿⣿⣿⣿⣿⣛⣳⣤⣀⣀   "
	           "   ⢠⣧⣶⣥⡤⢄ ⣸⣿⣿⠘  ⢀⣴⣿⣿⡿⠛⣿⣿⣧⠈⢿⠿⠟⠛⠻⠿⠄  "
	           "  ⣰⣿⣿⠛⠻⣿⣿⡦⢹⣿⣷   ⢊⣿⣿⡏  ⢸⣿⣿⡇ ⢀⣠⣄⣾⠄   "
	           " ⣠⣿⠿⠛ ⢀⣿⣿⣷⠘⢿⣿⣦⡀ ⢸⢿⣿⣿⣄ ⣸⣿⣿⡇⣪⣿⡿⠿⣿⣷⡄  "
	           " ⠙⠃   ⣼⣿⡟  ⠈⠻⣿⣿⣦⣌⡇⠻⣿⣿⣷⣿⣿⣿ ⣿⣿⡇ ⠛⠻⢷⣄ "
	           "      ⢻⣿⣿⣄   ⠈⠻⣿⣿⣿⣷⣿⣿⣿⣿⣿⡟ ⠫⢿⣿⡆     "
	           "       ⠻⣿⣿⣿⣿⣶⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⡟⢀⣀⣤⣾⡿⠃     "
	           "                                   "))
         (longest-line (apply #'max (mapcar #'length banner))))
    (put-text-property
     (point)
     (dolist (line banner (point))
       (insert (+doom-dashboard--center
                +doom-dashboard--width
                (concat line (make-string (max 0 (- longest-line (length line))) 32)))
               "\n"))
     'face 'doom-dashboard-banner)))

(setq +doom-dashboard-ascii-banner-fn #'dysthesis/dashboard-setup)
#+end_src
** Font
Doom exposes five (optional) variables for controlling fonts in Doom:

- =doom-font=: the primary font to use
- =doom-variable-pitch-font=: a non-monospace font (where applicable)
- =doom-big-font=: used for =doom-big-font-mode=; use this for presentations or streaming.
- =doom-symbol-font=: for symbols
- =doom-serif-font=: for the =fixed-pitch-serif= face

See =C-h v doom-font= for documentation and more examples of what they accept.

#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

(setq doom-font (font-spec :family "JetBrainsMono Nerd Font" :size 12.0 :weight 'medium)
      doom-variable-pitch-font (font-spec :family "Lato" :size 12.0 :weight 'medium))
#+end_src

*** Org-mode faces
#+begin_src emacs-lisp
(after! org (custom-set-faces!
              '(org-level-1 :foreground "#ffffff" :height 1.4 :weight bold)
              '(org-level-2 :foreground "#ffffff" :height 1.2 :weight bold)
              '(org-level-3 :foreground "#ffffff" :height 1.1 :weight bold)
              '(org-level-4 :foreground "#ffffff" :height 1.0 :weight bold)
              '(org-level-5 :foreground "#ffffff" :height 0.9 :weight bold)
              '(org-verbatim :foreground "LightGreen")
              '(org-quote :family "Lato" :height 1.0 :slant italic)
              '(org-time-grid :foreground "#ffffff")
              '(org-document-title :height 2.0 :foreground "#ffffff" :weight heavy)))
#+end_src

*** No underline for hl-line
#+begin_src emacs-lisp
(custom-set-faces!
  '(hl-line :underline nil))
#+end_src

*** Mixed pitch
#+begin_src emacs-lisp
(use-package mixed-pitch
  :hook
  ;; You might want to enable it only in org-mode or both text-mode and org-mode
  ((org-mode) . mixed-pitch-mode)
  :config
  (setq mixed-pitch-fixed-pitch-faces
        (append mixed-pitch-fixed-pitch-faces
                '(org-table
                  org-code
                  org-block
                  org-block-begin-line
                  org-block-end-line
                  org-meta-line
                  org-document-info-keyword
                  org-tag
                  org-time-grid
                  org-todo
                  org-done
                  org-agenda-date
                  org-date
                  org-drawer
                  org-modern-tag
                  org-modern-done
                  org-modern-label
                  org-scheduled
                  org-scheduled-today
                  neo-file-link-face
                  org-scheduled-previously)))
  (add-hook 'mixed-pitch-mode-hook #'solaire-mode-reset))
#+end_src

** Transparency
#+begin_src emacs-lisp
;; (set-frame-parameter nil 'alpha-background 50)
;; (add-to-list 'default-frame-alist '(alpha-background . 50))
#+end_src

** Doom theme
If you or Emacs can't find your font, use =M-x describe-font= to look them up, =M-x eval-region= to execute elisp code, and =M-x doom/reload-font= to refresh your font settings. If Emacs still can't find your font, it likely wasn't installed correctly. Font issues are rarely Doom issues!

There are two ways to load a theme. Both assume the theme is installed and available. You can either set =doom-theme= or manually load a theme with the =load-theme= function.

#+begin_src emacs-lisp
(setq doom-theme 'sweetpastel)
#+end_src

** Line numbering
This determines the style of line numbers in effect. If set to =nil=, line numbers are disabled. For relative line numbers, set this to =relative=.

#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
#+end_src

* Ivy :inactive:
#+begin_src emacs-lisp
;;(use-package! all-the-icons-ivy-rich
;;  :init (all-the-icons-ivy-rich-mode))
#+end_src

* IMenu
#+begin_src emacs-lisp
(setq imenu-list-focus-after-activation t)
(use-package! consult)
(map! :leader
      (:prefix ("s" . "Search")
       :desc "Menu to jump to places in buffer" "i" #'consult-imenu))

(map! :leader
      (:prefix ("t" . "Toggle")
       :desc "Toggle imenu shown in a sidebar" "i" #'imenu-list-smart-toggle))
#+end_src

* Org-mode
If you use =org= and don't want your org files in the default location below, change =org-directory=. It must be set before org loads!

#+begin_src emacs-lisp
(setq org-directory "~/Org/")
#+end_src

** Basic org-mode setup
#+begin_src emacs-lisp
(after! org
  (setq org-ellipsis " ↪")
  (setq org-startup-folded t))

(defun dysthesis/org-mode-setup ()
  (olivetti-mode)
  (display-line-numbers-mode 0)
  (olivetti-set-width 80)
  (setq-local company-backends (remove 'company-dabbrev company-backends))
  (setq-local company-backends (remove 'company-ispell company-backends)))
(add-hook 'org-mode-hook 'dysthesis/org-mode-setup)
#+end_src

** Notifications
#+begin_src emacs-lisp
;; (org-wild-notifier-mode)
#+end_src
** Org capture templates
Use DOCT (Declarative Org Capture Templates) for better capture template configuration.
#+begin_src emacs-lisp
(use-package! doct
  :commands doct)
#+end_src

Declare the capture templates
#+begin_src emacs-lisp
(after! org
  (setq org-capture-templates
        (doct '((" Todo"
                 :keys "t"
                 :prepend t
                 :file "GTD/inbox.org"
                 :headline "Tasks"
                 :type entry
                 :template ("* TODO %? %{extra}")
                 :children ((" General"
                             :keys "t"
                             :extra "")
                            ("󰈸 With deadline"
                             :keys "d"
                             :extra "\nDEADLINE: %^{Deadline:}t")
                            ("󰥔 With schedule"
                             :keys "s"
                             :extra "\nSCHEDULED: %^{Start time:}t")))
                ("Bookmark"
                 :keys "b"
                 :prepend t
                 :file "bookmarks.org"
                 :type entry
                 :template "* TODO [[%:link][%:description]] :bookmark:\n\n"
                 :immediate-finish t)))))
#+end_src

Make some quick shortcuts
#+begin_src emacs-lisp
(defun dysthesis/org-capture-todo ()
  (interactive)
  (org-capture nil "tt"))
(defun dysthesis/org-capture-todo-with-deadline ()
  (interactive)
  (org-capture nil "td"))
(defun dysthesis/org-capture-todo-with-schedule ()
  (interactive)
  (org-capture nil "ts"))

(bind-key "C-c t" #'dysthesis/org-capture-todo)
(bind-key "C-c d" #'dysthesis/org-capture-todo-with-deadline)
(bind-key "C-c s" #'dysthesis/org-capture-todo-with-schedule)
#+end_src

** Archiving
#+begin_src emacs-lisp
(setq org-archive-location "~/Org/archive.org::* From =%s=")
(defun dysthesis/org-archive-done-tasks ()
  "Archive all done tasks."
  (interactive)
  (org-map-entries 'org-archive-subtree "/DONE" 'file))
#+end_src

** Refile targets
#+begin_src emacs-lisp
(after! org
  (setq org-refile-targets '(("~/Org/GTD/gtd.org" :maxlevel . 3)
                           ("~/Org/GTD/someday.org" :level . 1)
                           ("~/Org/GTD/tickler.org" :maxlevel . 2)
                           ("~/Org/GTD/routine.org" :maxlevel . 2)
                           ("~/Org/GTD/reading.org" :maxlevel . 2))))
#+end_src

** Org-modern
#+begin_src emacs-lisp
;; Minimal UI
(package-initialize)
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)

;; Choose some fonts
(set-face-attribute 'default nil :family "JetBrainsMono Nerd Font")
(set-face-attribute 'variable-pitch nil :family "Lato")
;; (set-face-attribute 'org-modern-symbol nil :family "JetBrainsMono NF")

;; Add frame borders and window dividers
;; (modify-all-frames-parameters
;;  '((right-divider-width . 40)
;;    (internal-border-width . 40)))
(dolist (face '(window-divider
                window-divider-first-pixel
                window-divider-last-pixel))
  (face-spec-reset-face face)
  (set-face-foreground face (face-attribute 'default :background)))
(set-face-background 'fringe (face-attribute 'default :background))

(custom-declare-face
 '+org-todo-next
 '((t (:inherit (bold font-lock-constant-face org-todo)))) "")

(setq
 ;; Edit settings
 org-auto-align-tags nil
 org-tags-column 0
 org-fold-catch-invisible-edits 'show-and-error
 org-special-ctrl-a/e t
 org-insert-heading-respect-content t

 ;; TODO faces for org modern
 org-modern-todo-faces
 '(("WAIT"
    :inverse-video t
    :inherit +org-todo-onhold)
   ("NEXT"
    :inverse-video t
    :foreground "LightBlue")
   ("PROG"
    :inverse-video t
    :foreground "LightGreen")
   ("TODO"
    :inverse-video t
    :foreground "orange"))

 ;; Bullet symbols
 org-modern-list '((45 . "•")
                   (43 . "◈")
                   (42 . "➤"))
 org-modern-block-fringe t
 ;; Org-mode block names
 org-modern-block-name
 '((t . t)
   ("src" "»" "«")
   ("example" "»–" "–«")
   ("quote" "" "")
   ("export" "⏩" "⏪"))
 org-modern-keyword
 '((t . t)
   ("title" . "𝙏 ")
   ("filetags" . "󰓹 ")
   ("auto_tangle" . "󱋿 ")
   ("subtitle" . "𝙩 ")
   ("author" . "𝘼 ")
   ("email" . #(" " 0 1 (display (raise -0.14))))
   ("date" . "𝘿 ")
   ("property" . "☸ ")
   ("options" . "⌥ ")
   ("startup" . "⏻ ")
   ("macro" . "𝓜 ")
   ("bind" . #(" " 0 1 (display (raise -0.1))))
   ("bibliography" . " ")
   ("print_bibliography" . #(" " 0 1 (display (raise -0.1))))
   ("cite_export" . "⮭ ")
   ("print_glossary" . #("ᴬᶻ " 0 1 (display (raise -0.1))))
   ("glossary_sources" . #(" " 0 1 (display (raise -0.14))))
   ("include" . "⇤ ")
   ("setupfile" . "⇚ ")
   ("html_head" . "🅷 ")
   ("html" . "🅗 ")
   ("latex_class" . "🄻 ")
   ("latex_class_options" . #("🄻 " 1 2 (display (raise -0.14))))
   ("latex_header" . "🅻 ")
   ("latex_header_extra" . "🅻⁺ ")
   ("latex" . "🅛 ")
   ("beamer_theme" . "🄱 ")
   ("beamer_color_theme" . #("🄱 " 1 2 (display (raise -0.12))))
   ("beamer_font_theme" . "🄱𝐀 ")
   ("beamer_header" . "🅱 ")
   ("beamer" . "🅑 ")
   ("attr_latex" . "🄛 ")
   ("attr_html" . "🄗 ")
   ("attr_org" . "⒪ ")
   ("call" . #(" " 0 1 (display (raise -0.15))))
   ("name" . "⁍ ")
   ("header" . "› ")
   ("caption" . "☰ ")
   ("results" . "🠶"))
 ;; Org styling, hide markup etc.
 org-hide-emphasis-markers t
 org-pretty-entities t

 ;; Agenda styling
 org-agenda-tags-column 0
 org-agenda-block-separator ?─
 org-agenda-time-grid
 '((daily today require-timed)
   (800 1000 1200 1400 1600 1800 2000)
   " ┄┄┄┄┄ " "┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄")
 org-agenda-current-time-string
 "⭠ now ─────────────────────────────────────────────────")

(global-org-modern-mode)
#+end_src

*** Org-modern-indent :inactive:
#+begin_src emacs-lisp
(use-package org-modern-indent
 :config ; add late to hook
 (add-hook 'org-mode-hook #'org-modern-indent-mode 90))
#+end_src

** Org-agenda
*** Basic setup
#+begin_src emacs-lisp
(after! org-agenda
  (setq org-agenda-skip-scheduled-if-done t
        org-agenda-skip-deadline-if-done t
        org-agenda-include-deadlines t
        org-agenda-start-day "0d"
        org-agenda-block-separator nil
        org-agenda-compact-blocks t))
#+end_src
*** Org-agenda sorting strategy
#+begin_src emacs-lisp
(after! org
  (setq org-agenda-sorting-strategy
        '((urgency-up deadline-up priority-down effort-up))))
#+end_src
*** Org-agenda files
Set all Org files under the =~/Org/GTD= directory org-agenda file.

#+begin_src emacs-lisp
(after! org
  (setq org-agenda-files (directory-files-recursively "~/Org/GTD/" "\\.org$")))
#+end_src

*** Todo keywords
You must wrap your configurations in =(after! org...)=, else it gets overwritten by Doom's defaults. See [[https://github.com/doomemacs/doomemacs/issues/2913][this issue on GitHub]]. Also, if Org-modern is enabled, the TODO faces must be configured there.

#+begin_src emacs-lisp
(after! org
  (setq org-todo-keywords
        '((sequence "TODO(t)" "NEXT(n)" "WAIT(w)" "PROG(p)" "|" "DONE(d)" "|" "CANCEL(c)"))))
#+end_src

*** GTD stuff
Stolen from [[https://github.com/jethrokuan/dots/blob/master/.doom.d/config.el][Jethro Kuan's Emacs configuration]], and slightly modified. This section of the configuration is responsible for managing inbox items in an Org-agenda view. When you press =r= in an agenda view, it will start finding any inbox items and iterate through it, prompting you for tags, categories, timestamp, and refile targets. If the tag =someday= is *not* present, it will ask for a scheduled or deadline time too.

How this version differs from Jethro's original version:
- For some reason, the original =mark-inbox-todos= does not work, because =org-agenda-bulk-mark-regexp= does not behave as expected. Therefore, we iterate through each TODO item in the agenda and get their categories instead.
- The original version does not have the ability to set a scheduled and deadline time.

#+begin_src emacs-lisp
(defun log-todo-next-creation-date (&rest ignore)
  "Log NEXT creation time in the property drawer under the key 'ACTIVATED'"
  (when (and (string= (org-get-todo-state) "NEXT")
             (not (org-entry-get nil "ACTIVATED")))
    (org-entry-put nil "ACTIVATED" (format-time-string "[%Y-%m-%d]"))))
(add-hook 'org-after-todo-state-change-hook #'log-todo-next-creation-date)

(defun dysthesis/mark-inbox-todos ()
  "Mark entries in the agenda whose category is 'inbox' for future bulk action."
  (let ((entries-marked 0)
        (regexp "inbox")  ; Set the search term to 'inbox'
        category-at-point)
    (save-excursion
      (goto-char (point-min))
      (goto-char (next-single-property-change (point) 'org-hd-marker))
      (while (re-search-forward regexp nil t)
        (setq category-at-point (get-text-property (match-beginning 0) 'org-category))
        (if (or (get-char-property (point) 'invisible)
                (not category-at-point))  ; Skip if category is nil
            (beginning-of-line 2)
          (when (string-match-p regexp category-at-point)
            (setq entries-marked (1+ entries-marked))
            (call-interactively 'org-agenda-bulk-mark))))
      (unless entries-marked
        (message "No entry matching 'inbox'.")))))

(defun dysthesis/get-current-todo-category ()
  "Get the 'org-category' property of the TODO item at the current cursor position."
  (interactive)
  (let ((category (get-text-property (point) 'org-category)))
    (if category
        (message "Current TODO's category: %s" category)
      (message "No category found for current TODO"))))

(setq org-log-done 'time
      org-log-into-drawer t
      org-log-state-notes-insert-after-drawers nil)

(defun dysthesis/org-process-inbox ()
  "Called in org-agenda-mode, processes all inbox items."
  (interactive)
  (dysthesis/mark-inbox-todos)
  (dysthesis/bulk-process-entries))

(defvar dysthesis/org-current-effort "1:00"
  "Current effort for agenda items.")

(defun dysthesis/my-org-agenda-set-effort (effort)
  "Set the effort property for the current headline."
  (interactive
   (list (read-string (format "EFFORT [%s]: " dysthesis/org-current-effort) nil nil dysthesis/org-current-effort)))
  (setq dysthesis/org-current-effort effort)
  (org-agenda-check-no-diary)
  (let* ((hdmarker (or (org-get-at-bol 'org-hd-marker)
                       (org-agenda-error)))
         (buffer (marker-buffer hdmarker))
         (pos (marker-position hdmarker))
         (inhibit-read-only t)
         newhead)
    (org-with-remote-undo buffer
      (with-current-buffer buffer
        (widen)
        (goto-char pos)
        (org-show-context 'agenda)
        (funcall-interactively 'org-set-effort nil dysthesis/org-current-effort)
        (end-of-line 1)
        (setq newhead (org-get-heading)))
      (org-agenda-change-all-lines newhead hdmarker))))

(defun dysthesis/org-agenda-process-inbox-item ()
  "Process a single item in the org-agenda."
  (org-with-wide-buffer
   (org-agenda-set-tags)
   (org-agenda-priority)

   ;; Get the marker for the current headline
   (let* ((hdmarker (org-get-at-bol 'org-hd-marker))
          (category (completing-read "Category: " '("University" "Home" "Tinkering" "Read"))))
     ;; Switch to the buffer of the actual Org file
     (with-current-buffer (marker-buffer hdmarker)
       (goto-char (marker-position hdmarker))
       ;; Set the category property
       (org-set-property "CATEGORY" category)

       ;; Check if the current item has the 'someday' tag
       (unless (member "someday" (org-get-tags))
         ;; Prompt for scheduled and deadline times
         (let ((scheduled-time (org-read-date nil nil nil "Scheduled Time: (leave blank if none)"))
               (deadline-time (org-read-date nil nil nil "Deadline Time: (leave blank if none)")))
           ;; Set scheduled time if provided
           (when (and scheduled-time (not (string= scheduled-time "")))
             (org-schedule nil scheduled-time))
           ;; Set deadline time if provided
           (when (and deadline-time (not (string= deadline-time "")))
             (org-deadline nil deadline-time)))
         ))

   (call-interactively 'dysthesis/my-org-agenda-set-effort)
   (org-agenda-refile nil nil t))))

(defun dysthesis/bulk-process-entries ()
  (let ())
  (if (not (null org-agenda-bulk-marked-entries))
      (let ((entries (reverse org-agenda-bulk-marked-entries))
            (processed 0)
            (skipped 0))
        (dolist (e entries)
          (let ((pos (text-property-any (point-min) (point-max) 'org-hd-marker e)))
            (if (not pos)
                (progn (message "Skipping removed entry at %s" e)
                       (cl-incf skipped))
              (goto-char pos)
              (let (org-loop-over-headlines-in-active-region) (funcall 'dysthesis/org-agenda-process-inbox-item))
              ;; `post-command-hook' is not run yet.  We make sure any
              ;; pending log note is processed.
              (when (or (memq 'org-add-log-note (default-value 'post-command-hook))
                        (memq 'org-add-log-note post-command-hook))
                (org-add-log-note))
              (cl-incf processed))))
        (org-agenda-redo)
        (unless org-agenda-persistent-marks (org-agenda-bulk-unmark-all))
        (message "Acted on %d entries%s%s"
                 processed
                 (if (= skipped 0)
                     ""
                   (format ", skipped %d (disappeared before their turn)"
                           skipped))
                 (if (not org-agenda-persistent-marks) "" " (kept marked)")))))

(defun dysthesis/org-inbox-capture ()
  (interactive)
  "Capture a task in agenda mode."
  (org-capture nil "i"))

(map! :map org-agenda-mode-map
      "i" #'org-agenda-clock-in
      "r" #'dysthesis/org-process-inbox
      "R" #'org-agenda-refile)
#+end_src

#+RESULTS:

*** Refresh org-agenda automatically
#+begin_src emacs-lisp
;; (defvar refresh-agenda-time-seconds 300)

;; (defvar refresh-agenda-timer nil
;;   "Timer for `refresh-agenda-timer-function' to reschedule itself, or nil.")

;; (defun refresh-agenda-timer-function ()
;;   ;; If the user types a command while refresh-agenda-timer
;;   ;; is active, the next time this function is called from
;;   ;; its main idle timer, deactivate refresh-agenda-timer.
;;   (when refresh-agenda-timer
;;     (cancel-timer refresh-agenda-timer))

;;   (org-agenda nil "o")

;;   (setq refresh-agenda-timer
;;     (run-with-idle-timer
;;       ;; Compute an idle time break-length
;;       ;; more than the current value.
;;       (time-add (current-idle-time) refresh-agenda-time-seconds)
;;       nil
;;       'refresh-agenda-timer-function)))

;; (run-with-idle-timer refresh-agenda-time-seconds t 'refresh-agenda-timer-function)
#+end_src
*** Org-agenda habit visualiser
#+begin_src emacs-lisp
(add-to-list 'org-modules 'org-habit t)
(setq modus-themes-deuteranopia nil) ; try with nil too
(setq modus-themes-org-agenda
          (quote ((event . (accented italic varied))
                  (scheduled . uniform)
                  (habit . traffic-light))))
#+end_src
*** Colourised calendar view
#+begin_src emacs-lisp
(defface busy-1  '((t :foreground "black" :background "#eceff1")) "")
(defface busy-2  '((t :foreground "black" :background "#cfd8dc")) "")
(defface busy-3  '((t :foreground "black" :background "#b0bec5")) "")
(defface busy-4  '((t :foreground "black" :background "#90a4ae")) "")
(defface busy-5  '((t :foreground "white" :background "#78909c")) "")
(defface busy-6  '((t :foreground "white" :background "#607d8b")) "")
(defface busy-7  '((t :foreground "white" :background "#546e7a")) "")
(defface busy-8  '((t :foreground "white" :background "#455a64")) "")
(defface busy-9  '((t :foreground "white" :background "#37474f")) "")
(defface busy-10 '((t :foreground "white" :background "#263238")) "")
(defadvice calendar-generate-month
    (after highlight-weekend-days (month year indent) activate)
  "Highlight weekend days"
  (dotimes (i 31)
    (let* ((org-files (directory-files-recursively "~/Org/GTD" "\\.org$"))
           (date (list month (1+ i) year))
           (count 0))
      (dolist (file org-files)
        (setq count (+ count (length (org-agenda-get-day-entries file date)))))
      (cond ((= count 0) ())
            ((= count 1) (calendar-mark-visible-date date 'busy-1))
            ((= count 2) (calendar-mark-visible-date date 'busy-2))
            ((= count 3) (calendar-mark-visible-date date 'busy-3))
            ((= count 4) (calendar-mark-visible-date date 'busy-4))
            ((= count 5) (calendar-mark-visible-date date 'busy-5))
            ((= count 6) (calendar-mark-visible-date date 'busy-6))
            ((= count 7) (calendar-mark-visible-date date 'busy-7))
            ((= count 8) (calendar-mark-visible-date date 'busy-8))
            ((= count 9) (calendar-mark-visible-date date 'busy-9))
            (t  (calendar-mark-visible-date date 'busy-10)))
      )))
#+end_src

** Org-super-agenda
*** Setup
#+begin_src emacs-lisp
(after! org-agenda
  (setq org-super-agenda-keep-order t))
#+end_src

*** Agenda views
#+begin_src emacs-lisp
(after! org-agenda
  (let ((inhibit-message t))
    (org-super-agenda-mode)))

(setq org-agenda-custom-commands
      '(("o" "Overview"
         ((agenda "" ((org-agenda-span 'day)
                      (org-super-agenda-groups
                       '((:name "Today"
                          :time-grid t
                          :deadline today
                          :scheduled today
                          :order 0)
                         (:habit t
                          :order 1)
                         (:name "Overdue"
                          :deadline past
                          :scheduled past
                          :order 2)
                         (:name "Upcoming"
                          :time-grid t
                          :scheduled future
                          :deadline future
                          :order 3)))))
          (alltodo "" ((org-agenda-overriding-header "")
                       (org-super-agenda-groups
                        '((:name "Ongoing"
                           :todo "PROG"
                           :order 0)
                          (:name "Up next"
                           :todo "NEXT"
                           :order 1)
                          (:name "Waiting"
                           :todo "WAIT"
                           :order 2)
                          (:name "Important"
                           :priority "A"
                           :order 3)
                          (:name "Inbox"
                           :file-path "inbox"
                           :order 4)
                          (:name "University"
                           :category "University"
                           :tag ("university"
                                 "uni"
                                 "assignment"
                                 "exam")
                           :order 5)
                          (:name "Tinkering"
                           :category "Tinkering"
                           :tag ("nix"
                                 "nixos"
                                 "gentoo"
                                 "emacs"
                                 "tinker")
                           :order 6)
                          (:name "Reading list"
                           :category "Read"
                           :tag "read"
                           :order 6)))))))))
(defun dysthesis/agenda ()
  (interactive)
  (org-agenda nil "o"))

(use-package! org-agenda
  :init
  (map! "C-c a" #'dysthesis/agenda))
#+end_src

** Org-roam
A plain-text personal knowledge management system. Mimics the bidirectional linking capabilities of note-taking apps like Roam Research, Obsidian, or Logseq.

*** Initialisation
Initialise Org-roam and use v2.
#+begin_src emacs-lisp
(use-package org-roam
  :ensure t
  :init
  (setq org-roam-v2-ack t)
#+end_src

*** Variables
**** Roam directory
Define a directory to place Org-roam notes in
#+begin_src emacs-lisp
  :custom
  (org-roam-directory "~/Org/Roam")
#+end_src

**** Org-roam-dailies
Define capture templates and the directory for Org-roam-dailies.
#+begin_src emacs-lisp
  (org-roam-dailies-capture-templates
      '(("d" "default" entry "* %<%H:%M> %?"
         :if-new (file+head "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n"))))
  (org-roam-dailies-directory "Daily/")
#+end_src

****  Completion
Enable completion everywhere.
#+begin_src emacs-lisp
  (org-roam-completion-everywhere t)
#+end_src

*** Keybinding

| Keybinding       | Function name                      | Description                                                       |
|------------------+------------------------------------+-------------------------------------------------------------------|
| =C-c n l=          | =org-roam-buffer-toggle=             | Toggle the org-roam side buffer                                   |
| =C-c n f=          | =org-roam-node-find=                 | Find an org-roam node and open it                                 |
| =C-c n i= or =C-c i= | =org-roam-node-insert=               | Insert a link to an org-roam node                                 |
| =C-c n q=          | =org-roam-node-insert-immediate=     | Insert a link to an org-roam node without opening the edit buffer |
| =C-c n t=          | =org-roam-node-tag-add=              | Add a new tag to the current org-roam node                        |
| =C-c n c=          | =org-roam-capture=                   | Capture to an org-roam node                                       |
| =C-c n a=          | =org-roam-alias-add=                 | Add an alias to the current org-roam node                         |
| =C-M-i=            | =completion-at-point=                |                                                                   |
| =C-c n d t=        | =org-roam-dailies-capture-tomorrow=  | Capture to tomorrow's org-roam-dailies entry                      |
| =C-c n d y=        | =org-roam-dailies-capture-yesterday= | Capture to yesterday's org-roam-dailies entry                     |
| =C-c n d d=        | =org-roam-dailies-capture-today=     | Capture to today's org-roam-dailies entry                         |

#+begin_src emacs-lisp
  :bind
  (("C-c n l" . org-roam-buffer-toggle)
       ("C-c n f" . org-roam-node-find)
       ("C-c n i" . org-roam-node-insert)
       ("C-c i" . org-roam-node-insert)
       ("C-c n q" . org-roam-node-insert-immediate)
       ("C-c n t" . org-roam-tag-add)
       ("C-c n c" . org-roam-capture)
       ("C-c n a" . org-roam-alias-add)
       :map org-mode-map
       ("C-M-i"    . completion-at-point)
       :map org-roam-dailies-map
       ("y" . org-roam-dailies-capture-yesterday)
       ("t" . org-roam-dailies-capture-tomorrow))
  :bind-keymap
  ("C-c n d" . org-roam-dailies-map)
#+end_src

*** Configuration
Enable autosynchronisation of the Org-roam database.
#+begin_src emacs-lisp
  :config
  (org-roam-db-autosync-enable)
#+end_src

Force org-roam to use org-roam-dailies.
#+begin_src emacs-lisp
  (require 'org-roam-dailies)
#+end_src

**** Popup rules
#+begin_src emacs-lisp
  (set-popup-rules!
  `((,(regexp-quote org-roam-buffer) ; persistent org-roam buffer
     :side right :width .33 :height .5 :ttl nil :modeline nil :quit nil :slot 1)
    ("^\\*org-roam: " ; node dedicated org-roam buffer
     :side right :width .33 :height .5 :ttl nil :modeline nil :quit nil :slot 2))))
#+end_src

*** Capture templates
#+begin_src emacs-lisp
(setq org-roam-capture-templates
      '(("d" " Default" plain
         "%?"
         :if-new (file+head "${slug}.org"
                            "#+title: ${title}\n#+filetags: :new:\n#+STARTUP: latexpreview")
         :immediate-finish t
         :unnarrowed t)
        ("i" "󰆼 Index note" plain
         "%?"
         :if-new (file+head "${slug}.org"
                            "#+title: ${title}\n#+filetags: :new:index:")
         :immediate-finish t
         :unarrowed t)
        ("e" "󰖟 Elfeed" plain
         "%?"
         :target (file+head "Elfeed/${slug}.org"
                            "#+title: ${title}\n#+filetags: :new:article:rss:\n#+STARTUP: latexpreview"
                            ;;"#+filetags: :article:rss:\n"
                            )
         :unnarrowed t)
        ("l" "󰙨 Literature note" plain
         "%?"
         :target
         (file+head
          "%(expand-file-name (or citar-org-roam-subdir \"\") org-roam-directory)/Literature/${citar-citekey}.org"
          "#+title: ${note-title}.\n#+filetags: :new:\n#+created: %U\n#+last_modified: %U\n#+STARTUP: latexpreview\n\n* Annotations\n:PROPERTIES:\n:Custom_ID: ${citar-citekey}\n:NOTER_DOCUMENT: ${citar-file}\n:NOTER_PAGE: \n:END:\n\n")
         :unnarrowed t)
        ("d" " Idea" plain "%?"
         :if-new
         (file+head "${slug}.org" "#+title: ${title}\n#+filetags: :idea:new:\n#+STARTUP: latexpreview\n")
         :immediate-finish t
         :unnarrowed t)))
#+end_src
*** Quick note insertions without opening the new note buffer
This can be bound to any keybinding to quickly insert a new Org-roam note at the current point without opening the new note buffer, allowing you to just add the contents of it later.

#+begin_src emacs-lisp
(defun org-roam-node-insert-immediate (arg &rest args)
  (interactive "P")
  (let ((args (cons arg args))
        (org-roam-capture-templates (list (append (car org-roam-capture-templates)
                                                  '(:immediate-finish t)))))
    (apply #'org-roam-node-insert args)))
#+end_src

*** Org-roam-UI
A nice graph view to visualise connections in Org-roam notes. Similar to that of Obsidian or Logseq.

*Issue.* There appears to be an issue with XWidgets on NixOS, something to do with OpenGL. Therefore, for now, org-roam-ui /must/ be used inside a browser, by opening =http://127.0.0.1:35901/=.

#+begin_src emacs-lisp
(use-package! websocket
    :after org-roam)

(use-package! org-roam-ui
  :after org ;; or :after org
  ;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
  ;;         a hookable mode anymore, you're advised to pick something yourself
  ;;         if you don't care about startup time, use
  ;;  :hook (after-init . org-roam-ui-mode)
  :config
  (setq org-roam-ui-sync-theme t
        org-roam-ui-follow t
        org-roam-ui-update-on-save t
        ;; org-roam-ui-browser-function #'xwidget-webkit-browse-url ;; OpenGL issue on NixOS
        org-roam-ui-open-on-start t
        org-roam-ui-custom-theme
        '((bg-alt . "#181825")
          (bg . "#11111b")
          (fg . "#cdd6f4")
          (fg-alt . "#cdd6f4")
          (red . "#f38ba8")
          (orange . "#fab387")
          (yellow ."#f9e2af")
          (green . "#a6e3a1")
          (cyan . "#94e2d5")
          (blue . "#89b4fa")
          (violet . "#8be9fd")
          (magenta . "#f5c2e7"))))
#+end_src

*** Org-roam-dailies
Journaling made easy with Org-roam.

First, define the subfolder that daily notes should be stored in. This will be defined with respect to the =org-roam-directory=.
#+begin_src emacs-lisp
(setq org-roam-dailies-directory "Daily/")
#+end_src

*** Create a new task when a new note is made
#+begin_src emacs-lisp
(defun dysthesis/org-roam-capture-default
    (interactive)
  (org-roam-capture nil "d"))

#+end_src

*** Reviewing org-roam files
**** Filtering for =new= files.
#+begin_src emacs-lisp
(defun dysthesis/org-roam-find-new-notes ()
  (lambda (node)
    (member "new" (org-roam-node-tags node))))

(defun dysthesis/org-roam-process-notes ()
  (interactive)
  (org-roam-node-find nil nil (dysthesis/org-roam-find-new-notes)))

(bind-key "C-c m" #'dysthesis/org-roam-process-notes)
#+end_src

**** Getting rid of the =new= tags
#+begin_src emacs-lisp
(defun dysthesis/remove-new-tag ()
  "Remove the 'new' tag from the current Org-roam file."
  (interactive)
  (when (and (buffer-file-name) (org-roam-file-p))
    ;; Check if the 'new' tag is present and remove it
    (save-excursion
      (goto-char (point-min))
      (let ((tag-regex ":new:"))
        (while (re-search-forward tag-regex nil t)
          (replace-match ":")
          (save-buffer))))))

(bind-key "C-c r" #'dysthesis/remove-new-tag)
#+end_src

** Org-journal

** Miscellaneous
*** Org-protocol
#+begin_src emacs-lisp
(server-start)
(add-to-list 'load-path "~/Org/bookmark.org")
(require 'org-protocol)
#+end_src
*** Org-noter
Take notes for PDFs.

#+begin_src emacs-lisp
(use-package org-noter
  :after (:any org pdf-view)
  :config
  (setq
   ;; Please stop opening frames
   org-noter-always-create-frame nil
   ;; I want to see the whole file
   org-noter-hide-other nil
   ;; Everything is relative to the main notes file
   org-noter-notes-search-path (list org-directory)
   ))
#+end_src

*** Citations
**** Org-ref
#+begin_src emacs-lisp
(use-package! org-ref
    ;:after org-roam
    :config
    (setq
     org-ref-get-pdf-filename-function
      (lambda (key) (car (bibtex-completion-find-pdf key)))
     org-ref-default-bibliography (list "~/Org/Library.bib")
     ;;org-ref-bibliography-notes "~/Org/Roam/Literature/bibnotes.org"
     org-ref-pdf-directory "~/Documents/Library/files"
     org-ref-note-title-format "* %y - %t\n :PROPERTIES:\n  :Custom_ID: %k\n  :NOTER_DOCUMENT: %F\n :ROAM_KEY: cite:%k\n  :AUTHOR: %9a\n  :JOURNAL: %j\n  :YEAR: %y\n  :VOLUME: %v\n  :PAGES: %p\n  :DOI: %D\n  :URL: %U\n :END:\n\n"
     org-ref-notes-directory "~/Org/Roam/Literature"
     org-ref-notes-function 'orb-edit-notes))

(after! org-ref
(setq
 bibtex-completion-notes-path "~/Org/Roam/Literature/"
 bibtex-completion-bibliography "~/Org/Library.bib"
 bibtex-completion-library-path "~/Documents/Library/files/"
 bibtex-completion-pdf-field "file"
 bibtex-completion-notes-template-multiple-files
 (concat
  "#+TITLE: ${title}\n"
  "#+ROAM_KEY: cite:${=key=}\n"
  "* TODO Notes\n"
  ":PROPERTIES:\n"
  ":CUSTOM_ID: ${=key=}\n"
  ":NOTER_DOCUMENT: %(orb-process-file-field \"${=key=}\")\n"
  ":AUTHOR: ${author-abbrev}\n"
  ":JOURNAL: ${journaltitle}\n"
  ":DATE: ${date}\n"
  ":YEAR: ${year}\n"
  ":DOI: ${doi}\n"
  ":URL: ${url}\n"
  ":END:\n\n"
  )
 )
)
#+end_src

**** Citar-org-roam
#+begin_src emacs-lisp
(use-package citar
  :custom
  (citar-bibliography '("~/Org/Library.bib"))
  :hook
  (LaTeX-mode . citar-capf-setup)
  (org-mode . citar-capf-setup))

(setq citar-templates
      '((main . "${author editor:30%sn}     ${date year issued:4}     ${title:48}")
        (suffix . "          ${=key= id:15}    ${=type=:12}    ${tags keywords:*}")
        (preview . "${author editor:%etal} (${year issued date}) ${title}, ${journal journaltitle publisher container-title collection-title}.\n")
        (note . "Notes on ${author editor:%etal}, ${title}")))

(setq citar-org-roam-template-fields
  '((:citar-title . ("title"))
    (:citar-author . ("author" "editor"))
    (:citar-date . ("date" "year" "issued"))
    (:citar-pages . ("pages"))
    (:citar-type . ("=type="))
    (:citar-file . ("file"))))

(use-package citar-org-roam
  :after (citar org-roam)
  :config (citar-org-roam-mode))
(setq citar-org-roam-capture-template-key "l")
(setq citar-org-roam-note-title-template "${author} - ${title}")

(bind-key "C-c o" #'citar-open)
#+end_src
**** Org
#+begin_src emacs-lisp
(defun my-citar-org-open-notes (key entry)
  (let* ((bib (string-join (list my/bibtex-directory key ".bib")))
         (org (string-join (list my/bibtex-directory key ".org")))
         (new (not (file-exists-p org))))
    (funcall citar-file-open-function org)
    (when (and new (eq (buffer-size) 0))
      (insert (format template
                      (assoc-default "title" entry)
                      user-full-name
                      user-mail-address
                      bib
                      (with-temp-buffer
                        (insert-file-contents bib)
                        (buffer-string))))
      (search-backward "|")
      (delete-char 1))))

(setq-default citar-open-note-function 'my-citar-org-open-notes)
#+end_src

*** Org-fragtog
Automatic toggling of LaTeX fragments in Org-mode. When your cursor goes through a LaTeX fragment, the plugin de-renders it and shows the original code. Otherwise, render it as LaTeX.

#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'org-fragtog-mode)
#+end_src

*** Auto-tangle
Enable =org-auto-tangle= and automatically enable =org-auto-tangle-mode= on every =org-mode= buffers.

#+begin_src emacs-lisp
(use-package org-auto-tangle
  :defer t
  :hook (org-mode . org-auto-tangle-mode))
#+end_src
* LaTeX
** Higher resolution Org-mode LaTeX preview
#+begin_src emacs-lisp
;; (setq org-format-latex-options (plist-put org-format-latex-options :scale 1.5))
#+end_src

** Make Org-mode LaTeX previews work better with black themes
#+begin_src emacs-lisp
(plist-put org-format-latex-options :foreground "White")
(plist-put org-format-latex-options :background nil)
#+end_src

** Highlight LaTeX fragments
#+begin_src emacs-lisp
(setq org-highlight-latex-and-related '(latex script entities))
#+end_src

** Preview TikZ plots
#+begin_src emacs-lisp
(add-to-list 'org-latex-packages-alist
             '("" "tikz" t))

(eval-after-load "preview"
  '(add-to-list 'preview-default-preamble "\\PreviewEnvironment{tikzpicture}" t))

(after! org
  (setq org-latex-create-formula-image-program 'dvisvgm))
#+end_src

* Nov.el
A major mode for reading EPUB files in Emacs.

#+begin_src emacs-lisp
(use-package! nov
  :mode ("\\.epub\\'" . nov-mode)
  :config
  (map! :map nov-mode-map
        :n "RET" #'nov-scroll-up)

  (defun doom-modeline-segment--nov-info ()
    (concat
     " "
     (propertize
      (cdr (assoc 'creator nov-metadata))
      'face 'doom-modeline-project-parent-dir)
     " "
     (cdr (assoc 'title nov-metadata))
     " "
     (propertize
      (format "%d/%d"
              (1+ nov-documents-index)
              (length nov-documents))
      'face 'doom-modeline-info)))

  (advice-add 'nov-render-title :override #'ignore)

  (defun +nov-mode-setup ()
    "Tweak nov-mode to our liking."
    (face-remap-add-relative 'variable-pitch
                             :family "Georgia Pro"
                             :height 1.4)
    (face-remap-add-relative 'default :height 1.3)
    (setq-local line-spacing 0.2
                next-screen-context-lines 4
                shr-use-colors nil)
    (require 'visual-fill-column nil t)
    (setq-local visual-fill-column-center-text t
                visual-fill-column-width 81
                nov-text-width 80)
    (visual-fill-column-mode 1)
    (hl-line-mode -1)
    ;; Re-render with new display settings
    (nov-render-document)
    ;; Look up words with the dictionary.
    (add-to-list '+lookup-definition-functions #'+lookup/dictionary-definition)
    ;; Customise the mode-line to make it more minimal and relevant.
    (setq-local
     mode-line-format
     `((:eval
        (doom-modeline-segment--workspace-name))
       (:eval
        (doom-modeline-segment--window-number))
       (:eval
        (doom-modeline-segment--nov-info))
       ,(propertize
         " %P "
         'face 'doom-modeline-buffer-minor-mode)
       ,(propertize
         " "
         'face (if (doom-modeline--active) 'mode-line 'mode-line-inactive)
         'display `((space
                     :align-to
                     (- (+ right right-fringe right-margin)
                        ,(* (let ((width (doom-modeline--font-width)))
                              (or (and (= width 1) 1)
                                  (/ width (frame-char-width) 1.0)))
                            (string-width
                             (format-mode-line (cons "" '(:eval (doom-modeline-segment--major-mode))))))))))
       (:eval (doom-modeline-segment--major-mode)))))

  (add-hook 'nov-mode-hook #'+nov-mode-setup))
#+end_src

* Elfeed
RSS feed reader for Emacs. Useful for grabbing papers from ArXiV.
#+begin_src emacs-lisp
;; Load elfeed-org
(require 'elfeed-org)
(after! elfeed
  (elfeed-org)
  (use-package! elfeed-link)

  (setq
   elfeed-search-filter "@2-week-ago +unread"
   elfeed-search-print-entry-function '+rss/elfeed-search-print-entry
   elfeed-search-title-min-width 80
   elfeed-show-entry-switch #'pop-to-buffer
   elfeed-show-entry-delete #'+rss/delete-pane
   elfeed-show-refresh-function #'+rss/elfeed-show-refresh--better-style
   shr-max-image-proportion 0.6)

  (add-hook! 'elfeed-show-mode-hook (hide-mode-line-mode 1))
  (add-hook! 'elfeed-search-update-hook #'hide-mode-line-mode)
  (defface elfeed-show-title-face '((t (:weight ultrabold :slant italic :height 1.6)))
    "title face in elfeed show buffer"
    :group 'elfeed)
  (defface elfeed-show-author-face `((t (:weight light)))
    "title face in elfeed show buffer"
    :group 'elfeed)
  (set-face-attribute 'elfeed-search-title-face nil
                      :foreground "white"
                      :weight 'light)

  (defadvice! +rss-elfeed-wrap-h-nicer ()
    "Enhances an elfeed entry's readability by wrapping it to a width of
`fill-column' and centering it with `visual-fill-column-mode'."
    :override #'+rss-elfeed-wrap-h
    (setq-local truncate-lines nil
                shr-width 120
                next-screen-context-lines 4
                visual-fill-column-width 81
                visual-fill-column-center-text t
                default-text-properties '(line-height 1.5))
    (let ((inhibit-read-only t)
          (inhibit-modification-hooks t))
      (visual-fill-column-mode)
      (setq-local shr-current-font '(:family "Lato" :weight 'medium :height 1.5))
      (set-buffer-modified-p nil)))

  (defun +rss/elfeed-search-print-entry (entry)
    "Print ENTRY to the buffer."
    (let* ((elfeed-goodies/tag-column-width 30)
           (elfeed-goodies/feed-source-column-width 30)
           (elfeed-goodies/title-column-width 80) ;; Adjust this width as needed
           (title (or (elfeed-meta entry :title) (elfeed-entry-title entry) ""))
           (title-faces (elfeed-search--faces (elfeed-entry-tags entry)))
           (feed (elfeed-entry-feed entry))
           (feed-title
            (when feed
              (or (elfeed-meta feed :title) (elfeed-feed-title feed))))
           (tags (mapcar #'symbol-name (elfeed-entry-tags entry)))
           (tags-str (concat (mapconcat 'identity tags ",")))
           (title-column (elfeed-format-column
                          title (elfeed-clamp elfeed-goodies/title-column-width
                                              elfeed-goodies/title-column-width
                                              elfeed-goodies/title-column-width)
                          :left))
           (tag-column (elfeed-format-column
                        tags-str (elfeed-clamp (length tags-str)
                                               elfeed-goodies/tag-column-width
                                               elfeed-goodies/tag-column-width)
                        :left))
           (feed-column (elfeed-format-column
                         feed-title (elfeed-clamp elfeed-goodies/feed-source-column-width
                                                  elfeed-goodies/feed-source-column-width
                                                  elfeed-goodies/feed-source-column-width)
                         :left)))

      (insert (propertize feed-column 'face 'elfeed-search-feed-face) " ")
      (insert (propertize title-column 'face title-faces 'kbd-help title) " ")
      (insert (propertize tag-column 'face 'elfeed-search-tag-face))
      (setq-local line-spacing 0.2)))

  (defun +rss/elfeed-show-refresh--better-style ()
    "Update the buffer to match the selected entry, using a mail-style."
    (interactive)
    (let* ((inhibit-read-only t)
           (title (elfeed-entry-title elfeed-show-entry))
           (date (seconds-to-time (elfeed-entry-date elfeed-show-entry)))
           (author (elfeed-meta elfeed-show-entry :author))
           (link (elfeed-entry-link elfeed-show-entry))
           (tags (elfeed-entry-tags elfeed-show-entry))
           (tagsstr (mapconcat #'symbol-name tags ", "))
           (nicedate (format-time-string "%a, %e %b %Y %T %Z" date))
           (content (elfeed-deref (elfeed-entry-content elfeed-show-entry)))
           (type (elfeed-entry-content-type elfeed-show-entry))
           (feed (elfeed-entry-feed elfeed-show-entry))
           (feed-title (elfeed-feed-title feed))
           (base (and feed (elfeed-compute-base (elfeed-feed-url feed)))))
      (erase-buffer)
      (insert "\n")
      (insert (format "%s\n\n" (propertize title 'face 'elfeed-show-title-face)))
      (insert (format "%s\t" (propertize feed-title 'face 'elfeed-search-feed-face)))
      (when (and author elfeed-show-entry-author)
        (insert (format "%s\n" (propertize author 'face 'elfeed-show-author-face))))
      (insert (format "%s\n\n" (propertize nicedate 'face 'elfeed-log-date-face)))
      (when tags
        (insert (format "%s\n"
                        (propertize tagsstr 'face 'elfeed-search-tag-face))))
      ;; (insert (propertize "Link: " 'face 'message-header-name))
      ;; (elfeed-insert-link link link)
      ;; (insert "\n")
      (cl-loop for enclosure in (elfeed-entry-enclosures elfeed-show-entry)
               do (insert (propertize "Enclosure: " 'face 'message-header-name))
               do (elfeed-insert-link (car enclosure))
               do (insert "\n"))
      (insert "\n")
      (if content
          (if (eq type 'html)
              (elfeed-insert-html content base)
            (insert content))
        (insert (propertize "(empty)\n" 'face 'italic)))
      (goto-char (point-min)))))

(after! elfeed-search
  (set-evil-initial-state! 'elfeed-search-mode 'normal))
(after! elfeed-show-mode
  (set-evil-initial-state! 'elfeed-show-mode   'normal))

(after! evil-snipe
  (push 'elfeed-show-mode   evil-snipe-disabled-modes)
  (push 'elfeed-search-mode evil-snipe-disabled-modes))

(bind-key "C-c e" #'elfeed)
#+end_src

** Keybindings
#+begin_src emacs-lisp
(map! :map elfeed-search-mode-map
      :after elfeed-search
      [remap kill-this-buffer] "q"
      [remap kill-buffer] "q"
      :n doom-leader-key nil
      :n "q" #'+rss/quit
      :n "e" #'elfeed-update
      :n "r" #'elfeed-search-untag-all-unread
      :n "u" #'elfeed-search-tag-all-unread
      :n "s" #'elfeed-search-live-filter
      :n "RET" #'elfeed-search-show-entry
      :n "p" #'elfeed-show-pdf
      :n "+" #'elfeed-search-tag-all
      :n "-" #'elfeed-search-untag-all
      :n "S" #'elfeed-search-set-filter
      :n "b" #'elfeed-search-browse-url
      :n "y" #'elfeed-search-yank)
(map! :map elfeed-show-mode-map
      :after elfeed-show
      [remap kill-this-buffer] "q"
      [remap kill-buffer] "q"
      :n doom-leader-key nil
      :nm "q" #'+rss/delete-pane
      :nm "o" #'ace-link-elfeed
      :nm "RET" #'org-ref-elfeed-add
      :nm "n" #'elfeed-show-next
      :nm "N" #'elfeed-show-prev
      :nm "p" #'elfeed-show-pdf
      :nm "c" #'dysthesis/elfeed-capture-entry
      :nm "r" #'elfeed-show-refresh
      :nm "+" #'elfeed-show-tag
      :nm "-" #'elfeed-show-untag
      :nm "s" #'elfeed-show-new-live-search
      :nm "y" #'elfeed-show-yank)
#+end_src

** Elfeed-org
#+begin_src emacs-lisp
(setq rmh-elfeed-org-files (list "~/.config/doom/elfeed.org"))
#+end_src

** Elfeed-score
#+begin_src emacs-lisp
(require 'elfeed-score)
(elfeed-score-serde-load-score-file "~/.config/doom/elfeed.score")
(elfeed-score-enable)
(add-hook 'elfeed-search-mode-hook #'elfeed-score-score-search)
(define-key elfeed-search-mode-map "=" elfeed-score-map)
#+end_src

** Capture to Org-roam
#+begin_src emacs-lisp
(defun dysthesis/elfeed-capture-entry ()
  (interactive)
  ;; Check if we are in elfeed-show-mode
  (if (eq major-mode 'elfeed-show-mode)
      (let* ((entry elfeed-show-entry)  ; Get the current entry in elfeed-show
             (link (elfeed-entry-link entry))
             (title (elfeed-entry-title entry)))
        ;; Initiate an Org-roam capture
        (org-roam-capture- :keys "e" :node (org-roam-node-create :title title))
        (insert link))  ; Insert only the URL
    (message "Not in elfeed-show mode!")))
#+end_src

* Beancount
Finance tracking in Emacs.
#+begin_src emacs-lisp
(use-package! beancount
  :mode ("\\.beancount\\'" . beancount-mode)
  :init
  (after! all-the-icons
    (add-to-list 'all-the-icons-icon-alist
                 '("\\.beancount\\'" all-the-icons-material "attach_money" :face all-the-icons-lblue))
    (add-to-list 'all-the-icons-mode-icon-alist
                 '(beancount-mode all-the-icons-material "attach_money" :face all-the-icons-lblue)))
  :config
  (setq beancount-electric-currency t)
  (defun beancount-bal ()
    "Run bean-report bal."
    (interactive)
    (let ((compilation-read-command nil))
      (beancount--run "bean-report"
                      (file-relative-name buffer-file-name) "bal")))
  (map! :map beancount-mode-map
        :n "TAB" #'beancount-align-to-previous-number
        :i "RET" (cmd! (newline-and-indent) (beancount-align-to-previous-number))))
#+end_src

Stop =electric-indent= and =agressive-indent= from messing up Beancount's indenting.
#+begin_src emacs-lisp
(add-hook 'beancount-mode-hook
          (lambda () (setq-local electric-indent-chars nil)))
#+end_src

Activate =outline-minor-mode= for better navigation of Beancount files.
#+begin_src emacs-lisp
(add-hook 'beancount-mode-hook #'outline-minor-mode)
#+end_src

* LSP
** Nix
#+begin_src emacs-lisp
(use-package lsp-mode
  :ensure t)

(use-package nix-mode
  :hook (nix-mode . lsp-deferred)
  :ensure t)
#+end_src

*** Use Alejandra instead of nix-fmt
#+begin_src emacs-lisp
(set-formatter! 'alejandra '("alejandra" "--quiet") :modes '(nix-mode))

(after! apheleia
  (push '(alejandra . ("alejandra" "-")) apheleia-formatters)
  (setf (alist-get 'nix apheleia-mode-alist) 'alejandra))
#+end_src

** LSP UI
#+begin_src emacs-lisp
(use-package lsp-ui
  :init
  (setq lsp-ui-doc-enable nil)
  :bind (:map lsp-ui-mode-map
              ("C-c i" . lsp-ui-imenu)))
(add-hook! 'prog-mode-hook 'lsp-ui-mode)
#+end_src

* Company
Short for complete-anything, company is responsible for code completion in Doom Emacs.

To get code completion while working in a code block, use =C-c '= to open a new dedicated buffer with your cursor in the code block. When done, exit with =C-c C-c=.

#+begin_src emacs-lisp
(after! company
  (setq company-minimum-prefix-length 1
        company-idle-delay 0.05))
(set-company-backend! 'org-mode
      '(:separate company-capf
        :separate company-org-roam
        :separate company-yasnippet
        :separate company-files))
(setq-default history-length 1000)
(setq-default prescient-history-length 1000)
#+end_src
* Miscellaneous
** Rainbow mode
#+begin_src
(rainbow-mode 1)
#+end_src

** Aggressive indent mode
Automatically keep code properly indented and aligned, more agressive than electric-indent-mode.

#+begin_src emacs-lisp
(global-aggressive-indent-mode 1)
(add-to-list 'aggressive-indent-excluded-modes 'html-mode)
#+end_src

** Better copy-paste keybinds
#+begin_src emacs-lisp
(map! :ne "C-S-c" #'kill-ring-save
      :ne "C-S-v" #'yank)
#+end_src

** Default shell
#+begin_src emacs-lisp
(setq-default shell-file-name (executable-find "dash"))
#+end_src
